# Generated by Django 5.1.1 on 2024-11-05 10:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemarketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('hello', 'Hello'), ('bye', 'Bye')], max_length=6)),
                ('due_interval', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ')),
                ('text', models.TextField(default='https://t.me/Asaka_bank_bot')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('recipent', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ')),
                ('rating', models.IntegerField(default=-1)),
                ('is_answared', models.BooleanField(default=False)),
                ('language_code', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='en', max_length=2)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='telemarketing.appeal')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='playmobile.text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
