# Generated by Django 5.1.1 on 2024-11-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='agentgroup',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='agentinfo',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='agentposition',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='agentschedule',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
    ]
