# Generated by Django 5.1.1 on 2024-11-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_rename_updaetd_at_actiondescription_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldactionmapping',
            old_name='action_mode',
            new_name='action_code',
        ),
    ]
