# Generated by Django 5.1.1 on 2024-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_rename_action_mode_fieldactionmapping_action_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondescription',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actiondescription',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actiondescription',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
