# Generated by Django 5.1.1 on 2024-11-05 10:44

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('resourceId', models.CharField(max_length=56)),
                ('resourceName', models.CharField(max_length=128)),
                ('timeChangedStateMillis', models.BigIntegerField()),
                ('nHandledContacts', models.IntegerField()),
                ('nPresentedContacts', models.IntegerField()),
                ('avgTalkDuration', models.BigIntegerField()),
                ('longestTalkDuration', models.BigIntegerField()),
                ('avgHoldDuration', models.BigIntegerField()),
                ('longestHoldDuration', models.BigIntegerField()),
                ('avgWorkDuration', models.BigIntegerField()),
                ('totalTalkTime', models.BigIntegerField()),
                ('totalHoldTime', models.BigIntegerField()),
                ('maxReadyTime', models.BigIntegerField()),
                ('avgReadyTime', models.BigIntegerField()),
                ('totalReadyTime', models.BigIntegerField()),
                ('maxNotReadyTime', models.BigIntegerField()),
                ('avgNotReadyTime', models.BigIntegerField()),
                ('totalNotReadyTime', models.BigIntegerField()),
                ('maxWorkTime', models.BigIntegerField()),
                ('totalWorkTime', models.BigIntegerField()),
                ('logonDuration', models.BigIntegerField()),
                ('avgSpeedOfAnswer', models.IntegerField()),
                ('rsrcCurrentStateReason', models.CharField(blank=True, max_length=128, null=True)),
                ('activeOutboundTalkDuration', models.BigIntegerField()),
                ('avgOutboundTalkDuration', models.BigIntegerField()),
                ('avgOutboundHoldDuration', models.BigIntegerField()),
                ('activeOutboundHoldDuration', models.BigIntegerField()),
                ('longestOutboundTalkDuration', models.BigIntegerField()),
                ('longestOutboundHoldDuration', models.BigIntegerField()),
                ('totalOutboundTalkTime', models.BigIntegerField()),
                ('totalOutboundHoldTime', models.BigIntegerField()),
                ('avgOutboundWorkTime', models.BigIntegerField()),
                ('maxOutboundWorkTime', models.BigIntegerField()),
                ('totalOutboundWorkTime', models.BigIntegerField()),
                ('avgOutboundTalkWindow1', models.BigIntegerField()),
                ('avgOutboundHoldWindow1', models.BigIntegerField()),
                ('avgOutboundTalkWindow2', models.BigIntegerField()),
                ('avgOutboundHoldWindow2', models.BigIntegerField()),
                ('avgTalkingWindow1', models.BigIntegerField()),
                ('avgHoldWindow1', models.BigIntegerField()),
                ('avgTalkingWindow2', models.BigIntegerField()),
                ('avgHoldWindow2', models.BigIntegerField()),
                ('strResourceState', models.CharField(blank=True, max_length=128, null=True)),
                ('resourceBusySubState', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('created_at'), models.F('resourceId'), name='date_unique')],
            },
        ),
    ]
