# Generated by Django 5.1.1 on 2024-11-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemarketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='appeal',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='appealstatus',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='callscript',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='chouse',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='customercategory',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='customerstatus',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='optionobject',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='scriptcategory',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
    ]
