# Generated by Django 5.1.1 on 2024-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemarketing', '0002_alter_appeal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealstatus',
            name='name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='appealstatus',
            name='name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='appealstatus',
            name='name_uz',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='callscript',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='callscript',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='callscript',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='name_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='name_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='name_uz',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='name_uz',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='title_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='title_ru',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='title_uz',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scriptcategory',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_uz',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
