# Generated by Django 5.1.1 on 2024-11-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumoCardHistoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=16)),
                ('start_date', models.DateField(max_length=16)),
                ('end_date', models.DateField(max_length=16)),
            ],
            options={
                'verbose_name': 'HumoCardHistory',
                'verbose_name_plural': 'HumoCardHistories',
            },
        ),
        migrations.CreateModel(
            name='MasterCardHistoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=16)),
                ('start_date', models.DateField(max_length=16)),
                ('end_date', models.DateField(max_length=16)),
            ],
            options={
                'verbose_name': 'MasterCardHistory',
                'verbose_name_plural': 'MasterCardHistories',
            },
        ),
        migrations.CreateModel(
            name='UzcardHistroyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updaetd_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('page', models.IntegerField()),
                ('page_size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UzCardHistory',
                'verbose_name_plural': 'UzCardHistories',
            },
        ),
    ]
